# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from . import steps

RESULTS_URL = 'https://chromeperf.appspot.com'

SPEC = {
  'builders': {
    'Win ASan Release': {
      'chromium_config': 'chromium_win_clang_asan',
      'chromium_apply_config': ['mb', 'clobber'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 32,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-asan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'asan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'win' },
    },
    'Win ASan Release Coverage': {
      'chromium_config': 'chromium_win_clang_asan',
      'chromium_apply_config': ['mb', 'clobber', 'sanitizer_coverage'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 32,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-asan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'asan-coverage',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'win' },
    },
    'Win ASan Release Media': {
      'chromium_config': 'chromium_win_clang_asan',
      'chromium_apply_config': ['mb', 'clobber', 'chrome_with_codecs'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 32,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chrome-test-builds/media',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'asan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'win' },
    },
    'Win SyzyASAN LKGR': {
      'chromium_config': 'chromium_no_goma',
      'chromium_apply_config': ['clobber', 'mb', 'syzyasan'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 32,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-syzyasan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'asan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'win' },
    },
    # The build process for TSan is described at
    # http://dev.chromium.org/developers/testing/threadsanitizer-tsan-v2
    'TSAN Release': {
      'chromium_config': 'chromium_clang',
      'chromium_apply_config': ['mb', 'tsan2', 'clobber'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-tsan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'tsan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
    'TSAN Debug': {
      'chromium_config': 'chromium_clang',
      'chromium_apply_config': ['mb', 'tsan2', 'clobber'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Debug',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-tsan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'tsan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
    # The build process for MSan is described at
    # http://dev.chromium.org/developers/testing/memorysanitizer
    'MSAN Release (no origins)': {
      'chromium_config': 'chromium_clang',
      'chromium_apply_config': ['mb', 'msan', 'msan_no_origin_tracking',
                                'prebuilt_instrumented_libraries',
                                'sanitizer_coverage', 'clobber'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-msan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'msan-no-origins',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
    'MSAN Release (chained origins)': {
      'chromium_config': 'chromium_clang',
      'chromium_apply_config': ['mb', 'msan', 'msan_full_origin_tracking',
                                'prebuilt_instrumented_libraries',
                                'sanitizer_coverage', 'clobber'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-msan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'msan-chained-origins',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
    'UBSan Release': {
      'chromium_config': 'chromium_linux_ubsan',
      'chromium_apply_config': ['mb'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-ubsan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'ubsan',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
    # The build process for UBSan vptr is described at
    # http://dev.chromium.org/developers/testing/undefinedbehaviorsanitizer
    'UBSan vptr Release': {
      'chromium_config': 'chromium_linux_ubsan_vptr',
      'chromium_apply_config': ['mb'],
      'gclient_config': 'chromium',
      'chromium_config_kwargs': {
        'BUILD_CONFIG': 'Release',
        'TARGET_BITS': 64,
      },
      'bot_type': 'builder',
      'disable_tests': True,
      'cf_archive_build': True,
      'cf_gs_bucket': 'chromium-browser-ubsan',
      'cf_gs_acl': 'public-read',
      'cf_archive_name': 'ubsan-vptr',
      'cf_archive_subdir_suffix': 'vptr',
      'compile_targets': [ 'chromium_builder_asan' ],
      'testing': { 'platform': 'linux' },
    },
  },
}
