# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compile_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import goma_stats_pb2 as goma__stats__pb2
import counterz_pb2 as counterz__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='compile_events.proto',
  package='devtools_goma',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x63ompile_events.proto\x12\rdevtools_goma\x1a\x10goma_stats.proto\x1a\x0e\x63ounterz.proto\"\xb6\x02\n\x08StepInfo\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.devtools_goma.StepInfo.Status\x12\x46\n\x13goma_failure_reason\x18\x02 \x01(\x0e\x32).devtools_goma.StepInfo.GomaFailureReason\"1\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\r\n\tEXCEPTION\x10\x02\"\x7f\n\x11GomaFailureReason\x12\x0b\n\x07GOMA_OK\x10\x00\x12\x18\n\x14GOMA_UNKNOWN_FAILURE\x10\x01\x12\x16\n\x12GOMA_SETUP_FAILRUE\x10\x02\x12\x15\n\x11GOMA_PING_FAILURE\x10\x03\x12\x14\n\x10GOMA_BUILD_ERROR\x10\x04\"\xee\x02\n\x0c\x43ompileEvent\x12\x10\n\x08\x62uild_id\x18\x01 \x01(\x03\x12\x11\n\tstep_name\x18\x02 \x01(\t\x12*\n\tstep_info\x18\x07 \x01(\x0b\x32\x17.devtools_goma.StepInfo\x12\'\n\x05stats\x18\x03 \x01(\x0b\x32\x18.devtools_goma.GomaStats\x12?\n\x0b\x65xit_status\x18\x04 \x01(\x0e\x32*.devtools_goma.CompileEvent.GomaExitStatus\x12\x10\n\x08\x63rash_id\x18\x05 \x01(\t\x12\x34\n\x0e\x63ounterz_stats\x18\x06 \x01(\x0b\x32\x1c.devtools_goma.CounterzStats\"[\n\x0eGomaExitStatus\x12\x06\n\x02OK\x10\x00\x12\x1b\n\x17\x44IED_WITH_UNKOWN_REASON\x10\x01\x12\x0b\n\x07\x43RASHED\x10\x02\x12\x17\n\x13\x44IED_WITH_LOG_FATAL\x10\x03\x62\x06proto3')
  ,
  dependencies=[goma__stats__pb2.DESCRIPTOR,counterz__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STEPINFO_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='devtools_goma.StepInfo.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCEPTION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=206,
  serialized_end=255,
)
_sym_db.RegisterEnumDescriptor(_STEPINFO_STATUS)

_STEPINFO_GOMAFAILUREREASON = _descriptor.EnumDescriptor(
  name='GomaFailureReason',
  full_name='devtools_goma.StepInfo.GomaFailureReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOMA_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOMA_UNKNOWN_FAILURE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOMA_SETUP_FAILRUE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOMA_PING_FAILURE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOMA_BUILD_ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=257,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_STEPINFO_GOMAFAILUREREASON)

_COMPILEEVENT_GOMAEXITSTATUS = _descriptor.EnumDescriptor(
  name='GomaExitStatus',
  full_name='devtools_goma.CompileEvent.GomaExitStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIED_WITH_UNKOWN_REASON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRASHED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIED_WITH_LOG_FATAL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=662,
  serialized_end=753,
)
_sym_db.RegisterEnumDescriptor(_COMPILEEVENT_GOMAEXITSTATUS)


_STEPINFO = _descriptor.Descriptor(
  name='StepInfo',
  full_name='devtools_goma.StepInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='devtools_goma.StepInfo.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goma_failure_reason', full_name='devtools_goma.StepInfo.goma_failure_reason', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STEPINFO_STATUS,
    _STEPINFO_GOMAFAILUREREASON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=384,
)


_COMPILEEVENT = _descriptor.Descriptor(
  name='CompileEvent',
  full_name='devtools_goma.CompileEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_id', full_name='devtools_goma.CompileEvent.build_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step_name', full_name='devtools_goma.CompileEvent.step_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step_info', full_name='devtools_goma.CompileEvent.step_info', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats', full_name='devtools_goma.CompileEvent.stats', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exit_status', full_name='devtools_goma.CompileEvent.exit_status', index=4,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crash_id', full_name='devtools_goma.CompileEvent.crash_id', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counterz_stats', full_name='devtools_goma.CompileEvent.counterz_stats', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPILEEVENT_GOMAEXITSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=753,
)

_STEPINFO.fields_by_name['status'].enum_type = _STEPINFO_STATUS
_STEPINFO.fields_by_name['goma_failure_reason'].enum_type = _STEPINFO_GOMAFAILUREREASON
_STEPINFO_STATUS.containing_type = _STEPINFO
_STEPINFO_GOMAFAILUREREASON.containing_type = _STEPINFO
_COMPILEEVENT.fields_by_name['step_info'].message_type = _STEPINFO
_COMPILEEVENT.fields_by_name['stats'].message_type = goma__stats__pb2._GOMASTATS
_COMPILEEVENT.fields_by_name['exit_status'].enum_type = _COMPILEEVENT_GOMAEXITSTATUS
_COMPILEEVENT.fields_by_name['counterz_stats'].message_type = counterz__pb2._COUNTERZSTATS
_COMPILEEVENT_GOMAEXITSTATUS.containing_type = _COMPILEEVENT
DESCRIPTOR.message_types_by_name['StepInfo'] = _STEPINFO
DESCRIPTOR.message_types_by_name['CompileEvent'] = _COMPILEEVENT

StepInfo = _reflection.GeneratedProtocolMessageType('StepInfo', (_message.Message,), dict(
  DESCRIPTOR = _STEPINFO,
  __module__ = 'compile_events_pb2'
  # @@protoc_insertion_point(class_scope:devtools_goma.StepInfo)
  ))
_sym_db.RegisterMessage(StepInfo)

CompileEvent = _reflection.GeneratedProtocolMessageType('CompileEvent', (_message.Message,), dict(
  DESCRIPTOR = _COMPILEEVENT,
  __module__ = 'compile_events_pb2'
  # @@protoc_insertion_point(class_scope:devtools_goma.CompileEvent)
  ))
_sym_db.RegisterMessage(CompileEvent)


# @@protoc_insertion_point(module_scope)
