# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kythe/proto/java.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kythe.proto import storage_pb2 as kythe_dot_proto_dot_storage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kythe/proto/java.proto',
  package='kythe.proto',
  syntax='proto3',
  serialized_options=_b('\n\037com.google.devtools.kythe.protoZ\rjava_go_proto'),
  serialized_pb=_b('\n\x16kythe/proto/java.proto\x12\x0bkythe.proto\x1a\x19kythe/proto/storage.proto\"g\n\nJarDetails\x12(\n\x03jar\x18\x01 \x03(\x0b\x32\x1b.kythe.proto.JarDetails.Jar\x1a/\n\x03Jar\x12\"\n\x06v_name\x18\x01 \x01(\x0b\x32\x12.kythe.proto.VNameJ\x04\x08\x02\x10\x03\"(\n\x0fJarEntryDetails\x12\x15\n\rjar_container\x18\x01 \x01(\x05\"d\n\x0bJavaDetails\x12\x11\n\tclasspath\x18\x01 \x03(\t\x12\x12\n\nsourcepath\x18\x02 \x03(\t\x12\x15\n\rbootclasspath\x18\x03 \x03(\t\x12\x17\n\x0f\x65xtra_javacopts\x18\n \x03(\tB0\n\x1f\x63om.google.devtools.kythe.protoZ\rjava_go_protob\x06proto3')
  ,
  dependencies=[kythe_dot_proto_dot_storage__pb2.DESCRIPTOR,])




_JARDETAILS_JAR = _descriptor.Descriptor(
  name='Jar',
  full_name='kythe.proto.JarDetails.Jar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v_name', full_name='kythe.proto.JarDetails.Jar.v_name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=169,
)

_JARDETAILS = _descriptor.Descriptor(
  name='JarDetails',
  full_name='kythe.proto.JarDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jar', full_name='kythe.proto.JarDetails.jar', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JARDETAILS_JAR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=169,
)


_JARENTRYDETAILS = _descriptor.Descriptor(
  name='JarEntryDetails',
  full_name='kythe.proto.JarEntryDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jar_container', full_name='kythe.proto.JarEntryDetails.jar_container', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=211,
)


_JAVADETAILS = _descriptor.Descriptor(
  name='JavaDetails',
  full_name='kythe.proto.JavaDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classpath', full_name='kythe.proto.JavaDetails.classpath', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sourcepath', full_name='kythe.proto.JavaDetails.sourcepath', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bootclasspath', full_name='kythe.proto.JavaDetails.bootclasspath', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_javacopts', full_name='kythe.proto.JavaDetails.extra_javacopts', index=3,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=313,
)

_JARDETAILS_JAR.fields_by_name['v_name'].message_type = kythe_dot_proto_dot_storage__pb2._VNAME
_JARDETAILS_JAR.containing_type = _JARDETAILS
_JARDETAILS.fields_by_name['jar'].message_type = _JARDETAILS_JAR
DESCRIPTOR.message_types_by_name['JarDetails'] = _JARDETAILS
DESCRIPTOR.message_types_by_name['JarEntryDetails'] = _JARENTRYDETAILS
DESCRIPTOR.message_types_by_name['JavaDetails'] = _JAVADETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JarDetails = _reflection.GeneratedProtocolMessageType('JarDetails', (_message.Message,), dict(

  Jar = _reflection.GeneratedProtocolMessageType('Jar', (_message.Message,), dict(
    DESCRIPTOR = _JARDETAILS_JAR,
    __module__ = 'kythe.proto.java_pb2'
    # @@protoc_insertion_point(class_scope:kythe.proto.JarDetails.Jar)
    ))
  ,
  DESCRIPTOR = _JARDETAILS,
  __module__ = 'kythe.proto.java_pb2'
  # @@protoc_insertion_point(class_scope:kythe.proto.JarDetails)
  ))
_sym_db.RegisterMessage(JarDetails)
_sym_db.RegisterMessage(JarDetails.Jar)

JarEntryDetails = _reflection.GeneratedProtocolMessageType('JarEntryDetails', (_message.Message,), dict(
  DESCRIPTOR = _JARENTRYDETAILS,
  __module__ = 'kythe.proto.java_pb2'
  # @@protoc_insertion_point(class_scope:kythe.proto.JarEntryDetails)
  ))
_sym_db.RegisterMessage(JarEntryDetails)

JavaDetails = _reflection.GeneratedProtocolMessageType('JavaDetails', (_message.Message,), dict(
  DESCRIPTOR = _JAVADETAILS,
  __module__ = 'kythe.proto.java_pb2'
  # @@protoc_insertion_point(class_scope:kythe.proto.JavaDetails)
  ))
_sym_db.RegisterMessage(JavaDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
