# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from slave import recipe_test_api

import common

class GpuTestApi(recipe_test_api.RecipeTestApi):
  @property
  def dummy_swarm_hashes(self):
    return dict(
      (target, '[dummy hash for %s]' % target)
        for target in common.GPU_ISOLATES)

  # The following data was generated by running 'gyp_chromium
  # --analyzer' with input JSON files corresponding to changes
  # affecting these targets.

  @property
  def analyze_builds_nothing(self):
    return self.m.json.output({
        'status': 'No dependencies',
        'targets': [],
        'build_targets': []
        })

  @property
  def analyze_builds_gpu_unittests(self):
    return self.m.json.output({
        'status': 'Found dependency',
        'targets': ['gpu_unittests_run'],
        'build_targets': ['All', 'gpu_unittests']
        })

  @property
  def analyze_builds_everything(self):
    return self.m.json.output({
        'status': 'Found dependency',
        'targets': [u'%s_run' % test for test in common.GPU_ISOLATES],
        'build_targets': sorted((
          # A few random targets from the Chrome build to try to
          # confuse the recipe
          'All', 'app_list_demo', 'app_list_unittests', 'app_shell',
          'chrome_initial') +
          # The names of our isolates (even though telemetry_gpu_test
          # won't actually be reported by analyze)
          common.GPU_ISOLATES )
        })
