# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kythe/proto/buildinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kythe/proto/buildinfo.proto',
  package='kythe.proto',
  syntax='proto3',
  serialized_options=_b('\n\037com.google.devtools.kythe.protoZ\022buildinfo_go_proto'),
  serialized_pb=_b('\n\x1bkythe/proto/buildinfo.proto\x12\x0bkythe.proto\"M\n\x0c\x42uildDetails\x12\x14\n\x0c\x62uild_target\x18\x01 \x01(\t\x12\x11\n\trule_type\x18\x02 \x01(\t\x12\x14\n\x0c\x62uild_config\x18\x03 \x01(\tB5\n\x1f\x63om.google.devtools.kythe.protoZ\x12\x62uildinfo_go_protob\x06proto3')
)




_BUILDDETAILS = _descriptor.Descriptor(
  name='BuildDetails',
  full_name='kythe.proto.BuildDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_target', full_name='kythe.proto.BuildDetails.build_target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rule_type', full_name='kythe.proto.BuildDetails.rule_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_config', full_name='kythe.proto.BuildDetails.build_config', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['BuildDetails'] = _BUILDDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildDetails = _reflection.GeneratedProtocolMessageType('BuildDetails', (_message.Message,), dict(
  DESCRIPTOR = _BUILDDETAILS,
  __module__ = 'kythe.proto.buildinfo_pb2'
  # @@protoc_insertion_point(class_scope:kythe.proto.BuildDetails)
  ))
_sym_db.RegisterMessage(BuildDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
