DEPS = [
    'adb',
    'bisect_tester_staging',
    'buildbucket',
    'chromium',
    'chromium_android',
    'chromium_checkout',
    'chromium_swarming',
    'chromium_tests',
    'commit_position',
    'crrev',
    'depot_tools/bot_update',
    'depot_tools/gclient',
    'depot_tools/git',
    'depot_tools/tryserver',
    'file',
    'gitiles',
    'goma',
    'gsutil',
    'halt',
    'math_utils',
    'perf_dashboard',
    'perf_try_staging',
    'recipe_engine/json',
    'recipe_engine/path',
    'recipe_engine/platform',
    'recipe_engine/properties',
    'recipe_engine/python',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'service_account',
    'test_utils',
    'trigger',
    'url',
]


# TODO(phajdan.jr): provide coverage (http://crbug.com/693058).
DISABLE_STRICT_COVERAGE = True
