# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compile_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import goma_stats_pb2 as goma__stats__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='compile_events.proto',
  package='devtools_goma',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x63ompile_events.proto\x12\rdevtools_goma\x1a\x10goma_stats.proto\"\x8c\x02\n\x0c\x43ompileEvent\x12\x10\n\x08\x62uild_id\x18\x01 \x01(\t\x12\x11\n\tstep_name\x18\x02 \x01(\t\x12\'\n\x05stats\x18\x03 \x01(\x0b\x32\x18.devtools_goma.GomaStats\x12?\n\x0b\x65xit_status\x18\x04 \x01(\x0e\x32*.devtools_goma.CompileEvent.GomaExitStatus\x12\x10\n\x08\x63rash_id\x18\x05 \x01(\t\"[\n\x0eGomaExitStatus\x12\x06\n\x02OK\x10\x00\x12\x1b\n\x17\x44IED_WITH_UNKOWN_REASON\x10\x01\x12\x0b\n\x07\x43RASHED\x10\x02\x12\x17\n\x13\x44IED_WITH_LOG_FATAL\x10\x03\x62\x06proto3')
  ,
  dependencies=[goma__stats__pb2.DESCRIPTOR,])



_COMPILEEVENT_GOMAEXITSTATUS = _descriptor.EnumDescriptor(
  name='GomaExitStatus',
  full_name='devtools_goma.CompileEvent.GomaExitStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIED_WITH_UNKOWN_REASON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRASHED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIED_WITH_LOG_FATAL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=235,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_COMPILEEVENT_GOMAEXITSTATUS)


_COMPILEEVENT = _descriptor.Descriptor(
  name='CompileEvent',
  full_name='devtools_goma.CompileEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_id', full_name='devtools_goma.CompileEvent.build_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step_name', full_name='devtools_goma.CompileEvent.step_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats', full_name='devtools_goma.CompileEvent.stats', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exit_status', full_name='devtools_goma.CompileEvent.exit_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crash_id', full_name='devtools_goma.CompileEvent.crash_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPILEEVENT_GOMAEXITSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=326,
)

_COMPILEEVENT.fields_by_name['stats'].message_type = goma__stats__pb2._GOMASTATS
_COMPILEEVENT.fields_by_name['exit_status'].enum_type = _COMPILEEVENT_GOMAEXITSTATUS
_COMPILEEVENT_GOMAEXITSTATUS.containing_type = _COMPILEEVENT
DESCRIPTOR.message_types_by_name['CompileEvent'] = _COMPILEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompileEvent = _reflection.GeneratedProtocolMessageType('CompileEvent', (_message.Message,), dict(
  DESCRIPTOR = _COMPILEEVENT,
  __module__ = 'compile_events_pb2'
  # @@protoc_insertion_point(class_scope:devtools_goma.CompileEvent)
  ))
_sym_db.RegisterMessage(CompileEvent)


# @@protoc_insertion_point(module_scope)
